name: Check Packages

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check packages
        run: |
          sudo apt-get update
          apt-cache search protobuf | grep -i protobuf
          apt-cache search grpc | grep -i grpc 